# Generated by Django 5.0.1 on 2024-01-05 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                ("reg_no", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("clg_name", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("passing_year", models.IntegerField()),
                ("percentage", models.FloatField()),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.IntegerField()),
                ("fee_amount", models.IntegerField()),
                ("ad_date", models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
